[package]
name = "epilog"
description = "A collection of Prolog-like tools for inference logic."
version = "0.1.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]

[dev-dependencies]
proptest = "0.9.5"